import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * KyleHub Infrastructure Documentation Sidebar
 * 
 * Structure:
 * - Getting Started (quick start)
 * - Architecture (overview)
 * - Gateway VPS (VPS deployment)
 *   - Environment Configuration
 *   - Initial Configuration (Pangolin access)
 *   - Zitadel Setup (identity provider)
 *   - SMTP Setup (optional)
 * - Homelab (homelab deployment)
 *   - NEWT Connection
 *   - Adding Services
 * - Service Configuration (post-deployment)
 *   - Expose Services
 *   - Configure SSO
 *   - Zitadel Domain
 * - Troubleshooting
 * - Archive (legacy docs)
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;

