import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * KyleHub Infrastructure Documentation Sidebar
 * 
 * Structure:
 * - Getting Started (quick start)
 * - Architecture (overview)
 * - Gateway VPS (VPS deployment)
 * - Homelab (homelab deployment)
 * - Post-Deployment (configuration)
 * - Troubleshooting
 * - Archive (legacy docs)
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;

